---
apiVersion: v1
kind: Namespace
metadata:
  name: serverless
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  namespace: serverless
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
