---
apiVersion: v1
kind: Namespace
metadata:
  name: serverless
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: serverless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        ports:
        - containerPort: 80
